# Site settings
title: Chief Mustache Officer
email: hi@chiefmustacheofficer.com
description: > # this means to ignore newlines until "baseurl:"
  Marketing, revenue, leadership, and mustaches. Everything you need to grow your business in one place. :)
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: trevorlongino
github_username:  TheEnigmaticT

# Build settings
markdown: kramdown
plugins: [jekyll-paginate]

paginate: 4
paginate_path: "blog/page:num"
